apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: python-app-project

build:
  local:
    push: false
  artifacts:
    - image: python-app
      context: .
      docker:
        dockerfile: Dockerfile

profiles:
  - name: dev
    build:
      artifacts:
        - image: python-app
          context: .
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.py'
                dest: src
              - src: 'src/requirements.txt'
                dest: requirements.txt
    deploy:
      helm:
        releases:
          - name: python-app-release
            chartPath: charts/app
            namespace: default
            valuesFiles:
              - charts/app/values-dev.yaml
            setValues:
              image.repository: python-app
              image.pullPolicy: Never
    portForward:
      - resourceType: service
        resourceName: python-app-release
        namespace: default
        port: 8000
        localPort: 8000

  - name: prod
    build:
      artifacts:
        - image: python-app
          context: .
          docker:
            dockerfile: Dockerfile
    deploy:
      helm:
        releases:
          - name: python-app-release
            chartPath: charts/app
            namespace: default
            valuesFiles:
              - charts/app/values-prod.yaml
            setValues:
              image.repository: python-app
              image.pullPolicy: Never