apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: python-app-project # Changed

# Default artifact definitions.
build:
  local:
    push: false
  artifacts: # Updated
    - image: python-app
      context: .
      docker:
        dockerfile: Dockerfile

# Profiles define environment-specific configurations
profiles:
  - name: dev
    build:
      artifacts:
        - image: python-app
          context: .
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.py'
                dest: src # Copies to /app/src/ within the container
              - src: 'src/requirements.txt'
                dest: requirements.txt # Copies to /app/requirements.txt
    deploy:
      helm:
        releases:
          - name: python-app-release # Changed
            chartPath: charts/app
            namespace: default
            valuesFiles:
              - charts/app/values-dev.yaml
            setValues:
              image.repository: python-app # Changed
              image.pullPolicy: Never # Ensures Skaffold uses the locally built image and doesn't try to pull from a registry.
    portForward:
      - resourceType: service
        resourceName: python-app-release # Changed
        namespace: default
        port: 8000 # Changed
        localPort: 8000 # Changed

  - name: prod
    build:
      artifacts:
        - image: python-app
          context: .
          docker:
            dockerfile: Dockerfile
          # No sync for production
    deploy:
      helm:
        releases:
          - name: python-app-release # Changed
            chartPath: charts/app
            namespace: default
            valuesFiles:
              - charts/app/values-prod.yaml
            setValues:
              image.repository: python-app # Changed
              image.pullPolicy: Never # Ensures Skaffold uses the locally built image and doesn't try to pull from a registry.