# Default values for python-app.
replicaCount: 1

image:
  repository: python-app
  pullPolicy: Never
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}